#!/usr/bin/env bash
# Displays information about subdomains.
# Function to display information about a subdomain
display_info() {
    local subdomain="$2"
    local record_type="$3"
    local destination="$4"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Function to audit subdomains
audit_subdomains() {
    local domain="$1"
    local subdomain="$2"

    # Default subdomains to check
    subdomains=("www" "lb-01" "web-01" "web-02")

    # If a specific subdomain is provided, only check that subdomain
    if [ -n "$subdomain" ]; then
        subdomains=("$subdomain")
    fi

    # Iterate through subdomains
    for sub in "${subdomains[@]}"; do
    # Use awk to extract information from DNS lookup
    result=$(nslookup "$sub.$domain" | awk '/^Name:/{name=$2} /^Address:/{address=$2} END{print name " " address}')
    if [[ -n "$result" ]]; then
        subdomain_name=$(echo "$result" | awk '{print $1}' | cut -d'.' -f1)  # Extract only the subdomain name
        subdomain_ip=$(echo "$result" | awk '{print $2}')
        display_info "$subdomain_name" "A" "$subdomain_ip"
    else
        echo "No information found for $sub.$domain"
    fi
done
